/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_MOVE = 5;
  /** RegularExpression Id. */
  int T_TURNRIGHT = 6;
  /** RegularExpression Id. */
  int T_PUT = 7;
  /** RegularExpression Id. */
  int T_PICK = 8;
  /** RegularExpression Id. */
  int T_POP = 9;
  /** RegularExpression Id. */
  int T_SKIP = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int LOOP = 12;
  /** RegularExpression Id. */
  int REPEAT = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int DEFVAR = 15;
  /** RegularExpression Id. */
  int DEFUN = 16;
  /** RegularExpression Id. */
  int TURN = 17;
  /** RegularExpression Id. */
  int FACE = 18;
  /** RegularExpression Id. */
  int EQUALS = 19;
  /** RegularExpression Id. */
  int MOVE_DIR = 20;
  /** RegularExpression Id. */
  int RUN_DIRS = 21;
  /** RegularExpression Id. */
  int MOVE_FACE = 22;
  /** RegularExpression Id. */
  int FACING_P = 23;
  /** RegularExpression Id. */
  int CAN_PUT_P = 24;
  /** RegularExpression Id. */
  int CAN_PICK_P = 25;
  /** RegularExpression Id. */
  int CAN_MOVE_P = 26;
  /** RegularExpression Id. */
  int BLOCKED_P = 27;
  /** RegularExpression Id. */
  int FACE_TO = 28;
  /** RegularExpression Id. */
  int DIR = 29;
  /** RegularExpression Id. */
  int T_BALLOONS = 30;
  /** RegularExpression Id. */
  int T_CHIPS = 31;
  /** RegularExpression Id. */
  int NUMERO = 32;
  /** RegularExpression Id. */
  int WORD = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int LETTER = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"move\"",
    "\"turnright\"",
    "\"put\"",
    "\"pick\"",
    "\"pop\"",
    "\"skip\"",
    "\"if\"",
    "\"loop\"",
    "\"repeat\"",
    "\"not\"",
    "\"defvar\"",
    "\"defun\"",
    "\"turn\"",
    "\"face\"",
    "\"=\"",
    "\"move-dir\"",
    "\"run-dirs\"",
    "\"move_face\"",
    "\"facing-p\"",
    "\"can-put-p\"",
    "\"can-pick-p\"",
    "\"can-move-p\"",
    "\"blocked-p\"",
    "<FACE_TO>",
    "<DIR>",
    "\"ballons\"",
    "\"chips\"",
    "<NUMERO>",
    "<WORD>",
    "<DIGIT>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\":\"",
  };

}
