/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_MOVE = 5;
  /** RegularExpression Id. */
  int T_TURNRIGHT = 6;
  /** RegularExpression Id. */
  int T_PUT = 7;
  /** RegularExpression Id. */
  int T_PICK = 8;
  /** RegularExpression Id. */
  int T_POP = 9;
  /** RegularExpression Id. */
  int T_SKIP = 10;
  /** RegularExpression Id. */
  int STRUCTURE = 11;
  /** RegularExpression Id. */
  int DEFVAR = 12;
  /** RegularExpression Id. */
  int DEFUN = 13;
  /** RegularExpression Id. */
  int TURN = 14;
  /** RegularExpression Id. */
  int FACE = 15;
  /** RegularExpression Id. */
  int MOVE_DIR = 16;
  /** RegularExpression Id. */
  int RUN_DIRS = 17;
  /** RegularExpression Id. */
  int MOVE_FACE = 18;
  /** RegularExpression Id. */
  int TURN_TO = 19;
  /** RegularExpression Id. */
  int FACE_TO = 20;
  /** RegularExpression Id. */
  int DIR = 21;
  /** RegularExpression Id. */
  int T_BALLOONS = 22;
  /** RegularExpression Id. */
  int T_CHIPS = 23;
  /** RegularExpression Id. */
  int NUMERO = 24;
  /** RegularExpression Id. */
  int WORD = 25;
  /** RegularExpression Id. */
  int DIGIT = 26;
  /** RegularExpression Id. */
  int LETTER = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"move\"",
    "\"turnright\"",
    "\"put\"",
    "\"pick\"",
    "\"pop\"",
    "\"skip\"",
    "<STRUCTURE>",
    "\"defvar\"",
    "\"defun\"",
    "\"turn\"",
    "\"face\"",
    "\"move-dir\"",
    "\"run-dirs\"",
    "\"move_face\"",
    "<TURN_TO>",
    "<FACE_TO>",
    "<DIR>",
    "\"ballons\"",
    "\"chips\"",
    "<NUMERO>",
    "<WORD>",
    "<DIGIT>",
    "<LETTER>",
    "\"(\"",
    "\")\"",
    "\":\"",
  };

}
