/* Generated By:JavaCC: Do not edit this line. RobotTokenManager.java */
package uniandes.lym.robot.control;
import uniandes.lym.robot.kernel.*;
import java.awt.Point;
import java.io.*;
import java.util.Vector;
import java.util.LinkedList;
import java.util.HashMap;

/** Token Manager. */
public class RobotTokenManager implements RobotConstants
{

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0x87538be0L) != 0L)
         {
            jjmatchedKind = 33;
            return 39;
         }
         if ((active0 & 0x48000000L) != 0L)
         {
            jjmatchedKind = 33;
            return 30;
         }
         if ((active0 & 0x840000L) != 0L)
         {
            jjmatchedKind = 33;
            return 19;
         }
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 33;
            return 3;
         }
         if ((active0 & 0x1000L) != 0L)
         {
            jjmatchedKind = 33;
            return 26;
         }
         if ((active0 & 0x400L) != 0L)
         {
            jjmatchedKind = 33;
            return 11;
         }
         if ((active0 & 0x202000L) != 0L)
         {
            jjmatchedKind = 33;
            return 23;
         }
         return -1;
      case 1:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 29;
         }
         if ((active0 & 0x8ff7b7e0L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 39;
         }
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 1;
            return 2;
         }
         if ((active0 & 0x800L) != 0L)
            return 39;
         return -1;
      case 2:
         if ((active0 & 0xcff7b560L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 2;
            return 39;
         }
         if ((active0 & 0x4280L) != 0L)
            return 39;
         return -1;
      case 3:
         if ((active0 & 0x7200000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x561560L) != 0L)
            return 39;
         if ((active0 & 0xc881a000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 3;
            }
            return 39;
         }
         return -1;
      case 4:
         if ((active0 & 0x4880a040L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 4;
            return 39;
         }
         if ((active0 & 0x7200000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x80010000L) != 0L)
            return 39;
         return -1;
      case 5:
         if ((active0 & 0x7200000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x48800040L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 5;
            return 39;
         }
         if ((active0 & 0xa000L) != 0L)
            return 39;
         return -1;
      case 6:
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x7200000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x40000000L) != 0L)
            return 39;
         if ((active0 & 0x8000040L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 6;
            return 39;
         }
         return -1;
      case 7:
         if ((active0 & 0x40L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 7;
            return 39;
         }
         if ((active0 & 0x8000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x800000L) != 0L)
         {
            if (jjmatchedPos < 5)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 5;
            }
            return -1;
         }
         if ((active0 & 0x7200000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 2;
            }
            return -1;
         }
         return -1;
      case 8:
         if ((active0 & 0x8000000L) != 0L)
         {
            if (jjmatchedPos < 6)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 6;
            }
            return -1;
         }
         if ((active0 & 0x7000000L) != 0L)
         {
            if (jjmatchedPos < 2)
            {
               jjmatchedKind = 33;
               jjmatchedPos = 2;
            }
            return -1;
         }
         if ((active0 & 0x40L) != 0L)
            return 39;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 40:
         return jjStopAtPos(0, 36);
      case 41:
         return jjStopAtPos(0, 37);
      case 58:
         return jjStopAtPos(0, 38);
      case 61:
         return jjStopAtPos(0, 19);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0x48000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x87000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x18000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x840000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0x800L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x500020L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x380L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x202000L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x400L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x20040L);
      default :
         return jjMoveNfa_0(4, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x47840000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x1a000L);
      case 70:
      case 102:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(1, 11, 39);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x100L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa2_0(active0, 0x400L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x8000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa2_0(active0, 0x505220L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x2200c0L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 67:
      case 99:
         return jjMoveStringLiteralDfa3_0(active0, 0x840100L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa3_0(active0, 0x18000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000400L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x7200000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x8001000L);
      case 80:
      case 112:
         if ((active0 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(2, 9, 39);
         return jjMoveStringLiteralDfa3_0(active0, 0x2000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x20040L);
      case 84:
      case 116:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 39);
         else if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(2, 14, 39);
         break;
      case 86:
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x500020L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa4_0(active0, 0x7200000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000000L);
      case 69:
      case 101:
         if ((active0 & 0x20L) != 0L)
         {
            jjmatchedKind = 5;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 39);
         return jjMoveStringLiteralDfa4_0(active0, 0x502000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
      case 75:
      case 107:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 8, 39);
         break;
      case 76:
      case 108:
         return jjMoveStringLiteralDfa4_0(active0, 0x40000000L);
      case 78:
      case 110:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_0(active0, 0x40L);
      case 80:
      case 112:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(3, 10, 39);
         else if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(3, 12, 39);
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000L);
      case 95:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0xa000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x200000L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000L);
      case 78:
      case 110:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(4, 16, 39);
         return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x40000000L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa5_0(active0, 0x3000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x40L);
      case 83:
      case 115:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 31, 39);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 68:
      case 100:
         return jjMoveStringLiteralDfa6_0(active0, 0x100000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x8000000L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa6_0(active0, 0x400000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa6_0(active0, 0x800000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x2200040L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa6_0(active0, 0x40000000L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000L);
      case 82:
      case 114:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(5, 15, 39);
         break;
      case 84:
      case 116:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(5, 13, 39);
         break;
      case 85:
      case 117:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0x40L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x100000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa7_0(active0, 0x200000L);
      case 83:
      case 115:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(6, 30, 39);
         break;
      case 84:
      case 116:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa7_0(active0, 0x4000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa8_0(active0, 0x9000000L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x400000L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa8_0(active0, 0x4000000L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa8_0(active0, 0x40L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa8_0(active0, 0x2000000L);
      case 80:
      case 112:
         if ((active0 & 0x800000L) != 0L)
            return jjStopAtPos(7, 23);
         break;
      case 82:
      case 114:
         if ((active0 & 0x100000L) != 0L)
            return jjStopAtPos(7, 20);
         break;
      case 83:
      case 115:
         if ((active0 & 0x200000L) != 0L)
            return jjStopAtPos(7, 21);
         break;
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa9_0(active0, 0x6000000L);
      case 69:
      case 101:
         if ((active0 & 0x400000L) != 0L)
            return jjStopAtPos(8, 22);
         break;
      case 80:
      case 112:
         if ((active0 & 0x1000000L) != 0L)
            return jjStopAtPos(8, 24);
         else if ((active0 & 0x8000000L) != 0L)
            return jjStopAtPos(8, 27);
         break;
      case 84:
      case 116:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(8, 6, 39);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 80:
      case 112:
         if ((active0 & 0x2000000L) != 0L)
            return jjStopAtPos(9, 25);
         else if ((active0 & 0x4000000L) != 0L)
            return jjStopAtPos(9, 26);
         break;
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 40;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 4:
               case 38:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  kind = 32;
                  jjCheckNAdd(38);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(39);
                  }
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 29:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(39);
                  }
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 11:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(39);
                  }
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 3:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(39);
                  }
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 2;
                  break;
               case 23:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(39);
                  }
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 22;
                  break;
               case 19:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(39);
                  }
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 18;
                  break;
               case 30:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(39);
                  }
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 29;
                  break;
               case 4:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(39);
                  }
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  else if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  else if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  else if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  else if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  else if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  else if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  else if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  else if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 26:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 33)
                        kind = 33;
                     jjCheckNAdd(39);
                  }
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 25;
                  break;
               case 0:
                  if ((0x10000000100L & l) != 0L && kind > 28)
                     kind = 28;
                  break;
               case 1:
               case 9:
                  if ((0x10000000100000L & l) != 0L)
                     jjCheckNAdd(0);
                  break;
               case 5:
                  if ((0x10000000100000L & l) != 0L && kind > 28)
                     kind = 28;
                  break;
               case 6:
               case 13:
                  if ((0x8000000080000L & l) != 0L)
                     jjCheckNAdd(5);
                  break;
               case 7:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 7;
                  break;
               case 10:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 9;
                  break;
               case 12:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 11;
                  break;
               case 14:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 13;
                  break;
               case 15:
                  if ((0x80000000800000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 14;
                  break;
               case 16:
                  if ((0x10000000100000L & l) != 0L && kind > 29)
                     kind = 29;
                  break;
               case 17:
                  if ((0x400000004000L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 18:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 20:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 21:
                  if ((0x10000000100L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 22:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 21;
                  break;
               case 24:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 25:
                  if ((0x4000000040L & l) != 0L)
                     jjCheckNAdd(16);
                  break;
               case 27:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 28:
                  if ((0x80000000800L & l) != 0L && kind > 29)
                     kind = 29;
                  break;
               case 31:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 32:
                  if ((0x1000000010L & l) != 0L && kind > 29)
                     kind = 29;
                  break;
               case 33:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 32;
                  break;
               case 34:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 33;
                  break;
               case 35:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 35;
                  break;
               case 37:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 36;
                  break;
               case 39:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 33)
                     kind = 33;
                  jjCheckNAdd(39);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 40 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, "\75", null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, "\50", "\51", "\72", };

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0x73ffffffe1L, 
};
static final long[] jjtoSkip = {
   0x1eL, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[40];
private final int[] jjstateSet = new int[80];
protected char curChar;
/** Constructor. */
public RobotTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}

/** Constructor. */
public RobotTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 40; i-- > 0;)
      jjrounds[i] = 0x80000000;
}

/** Reinitialise parser. */
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}

/** Switch to specified lex state. */
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

}
